name: Build and Deploy
on:
  push:
  #schedule:
  #  - cron: '0 * * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Create manifest
        uses: knoxfighter/generate-loading-screen@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@4.1.5
#        with:
#          branch: out # The branch the action should deploy to.
#          folder: .build # The folder the action should deploy.
